-- ============================================================
-- FieldMoisturePanel.lua
-- Intentionally minimal placeholder.
--
-- All HUD rendering is handled by src/HUDOverlay.lua using FS25
-- immediate-mode render calls (renderText + renderOverlay via a
-- shared 1×1 white-pixel overlay created by createImageOverlay).
--
-- Future upgrade path (if resolution-independent theming is needed):
--   Replace HUDOverlay's immediate-mode draw with a proper GuiElement
--   panel loaded from FieldMoisturePanel.xml. Steps:
--   1. Create FieldMoisturePanel.xml following TakeLoanDialog.xml pattern
--   2. Register via g_gui:loadGui() in loadMission00Finished
--   3. In HUDOverlay:initialize(), switch to g_gui:showDialog()
--   4. Remove renderText/renderOverlay calls from HUDOverlay:draw()
-- ============================================================

-- No-op — HUDOverlay.lua handles all rendering
